### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Milo123459** [pksunkara/cargo-up#9]
I get errors like this:

![img](https://salvage.is-inside.me/5sgTjoSw.png)

**Comment by Milo123459** [comment]
I'm using latest version of Rust btw.

**Comment by pksunkara** [comment]
I am actually not sure what's happening here. Are you able to install from source after cloning instead?

**Comment by pksunkara** [comment]
Wait, I might know what's happening. [This](https://github.com/pksunkara/cargo-up/blob/master/cargo-up/src/lib/mod.rs#L1) line is not actually excluding `lib` stuff.

Try running the following command:

```sh
cargo install cargo-up --features cli
```

Also, please try to use the source code after cloning instead of relying on published versions. It's very early.

**Comment by Milo123459** [comment]
Yea that worked.

**Comment by pksunkara** [comment]
I will fix it differently

**Comment by pksunkara** [comment]
Fixed with latest release.
